version: '3.8'

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  postgres:
    image: 'postgres:14'
    container_name: 'postgres-db'
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    environment:
      POSTGRES_BD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Kirill"
