spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL:localhost:5432}/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Kirill}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
  liquibase:
    enabled: true
    drop-first: false
server:
  port: 9090
