spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL:localhost:5432}/pi
    username: ${DB_USER:pi}
    password: ${DB_PASSWORD:raspberry}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: true
  liquibase:
    enabled: true
    drop-first: true
server:
  port: 9090
